---
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/module:
  - changed-files:
      - any-glob-to-any-file: modules/**/*
area/vscode:
  - changed-files:
      - any-glob-to-any-file: .vscode/**/*
area/tasks:
  - changed-files:
      - any-glob-to-any-file: .tasks/**/*
area/documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**/*
area/definitions:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**/*
          - "*.tf"
